name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: Run backend tests
      run: npm test
      working-directory: ./backend

    - name: Build frontend
      run: npm run build
      working-directory: ./frontend

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f ci-cd/kubernetes/backend-deployment.yaml
        kubectl apply -f ci-cd/kubernetes/frontend-deployment.yaml
        kubectl apply -f ci-cd/kubernetes/backend-service.yaml
        kubectl apply -f ci-cd/kubernetes/frontend-service.yaml
